#!/usr/bin/env bash
# Generate superwriter/references/voices.md, the annotated voice list read on
# `/superwriter list`. Each row is a profile's title and its "Furthest from
# neutral" line. Re-run after adding, removing, or renaming a profile;
# scripts/validate_skill.sh fails if the committed file is out of date.
#
# Usage: scripts/build_index.sh [output-path]   (default: the committed voices.md)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REF="$ROOT/superwriter/references"
OUT="${1-}"
[ -n "$OUT" ] || OUT="$REF/voices.md"

emit_category() {
  local dir="$1" heading="$2" f title fn started=0
  [ -d "$REF/$dir" ] || return 0
  while IFS= read -r f; do
    [ "$(basename "$f")" = "README.md" ] && continue
    if [ "$started" -eq 0 ]; then
      printf '\n## %s\n\n| Voice | Furthest from neutral |\n|---|---|\n' "$heading"
      started=1
    fi
    title=$(grep -m1 '^# ' "$f" | sed 's/^# //' || true)
    fn=$(grep -m1 '^\*\*Furthest from neutral:\*\* ' "$f" | sed 's/^\*\*Furthest from neutral:\*\* //' || true)
    if [ -z "$title" ] || [ -z "$fn" ]; then
      echo "build_index: $f is missing a '# Title' or '**Furthest from neutral:**' line" >&2
      exit 1
    fi
    printf '| %s | %s |\n' "$title" "$fn"
  done < <(find "$REF/$dir" -maxdepth 1 -type f -name '*.md' | LC_ALL=C sort)
}

{
  printf '<!-- generated by scripts/build_index.sh - do not edit -->\n'
  printf '# Voices\n'
  emit_category authors Authors
  emit_category registers Registers
  emit_category forms Forms
  emit_category custom Custom
} > "$OUT"

echo "wrote $OUT"
